module.exports = {
    academy: [
        'index',
        {
            type: 'category',
            label: 'Web scraping & Automation',
            // link: {
            //     type: 'generated-index',
            //     title: 'Web scraping & Automation',
            //     slug: '/web-scraping-and-automation',
            //     keywords: ['web scraping', 'automation'],
            // },
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'webscraping',
                },
            ],
        },
        {
            type: 'category',
            label: 'Apify Platform',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'platform',
                },
            ],
        },
        {
            type: 'category',
            label: 'Tutorials',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials',
                },
            ],
        },
        {
            type: 'category',
            label: 'Glossary',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'glossary',
                },
            ],
        },
    ],
};
