name: publish-theme

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js 16
                uses: actions/setup-node@v2-beta
                with:
                    node-version: 16

            -   name: Build & deploy docs
                run: |
                  ( ./tools/hasChanged.sh ./theme/package.json && 
                  cd ./theme && npm publish --access=public | cd ../
                  ) ||
                  echo "No theme updates found, closing!";
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GIT_USER: "barjin:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
