name: publish-theme

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        outputs:
            theme_changed: ${{ steps.changed-theme-files.outputs.any_changed }}

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Use Node.js 16
                uses: actions/setup-node@v2-beta
                with:
                    node-version: 16

            -   name: Setup git user and npm
                run: |
                    git config --global user.name "Apify Release Bot"
                    git config --global user.email "noreply@apify.com"
                    
                    cd $GITHUB_WORKSPACE/apify-docs-theme
                    echo "access=public" > .npmrc
                    echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

            -   name: Deploy theme to npm
                run: |
                    cd $GITHUB_WORKSPACE/apify-docs-theme
                    npx -y publish-if-not-exists
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GIT_USER: "barjin:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
            
            - name: Get changed files in the docs folder
              id: changed-theme-files
              uses: tj-actions/changed-files@v35
              with:
                files: |
                    apify-docs-theme/**
    
    rebuild-docs:
        needs: publish
        if: needs.publish.outputs.theme_changed == 'true'
        strategy:
            matrix:
                repo: ['apify/apify-sdk-js-v2']
        runs-on: ubuntu-latest
        steps: 
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v2
              with:
                token: ${{ secrets.GH_TOKEN }}
                repository: ${{ matrix.repo }}
                event-type: rebuild-docs