module.exports = {
    academy: [
        'index',
        {
            type: 'category',
            label: 'Web scraping & Automation',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'webscraping',
                },
            ],
        },
        {
            type: 'category',
            label: 'Apify Platform',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'platform',
                },
            ],
        },
        {
            type: 'category',
            label: 'Tutorials',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials',
                },
            ],
        },
        {
            type: 'category',
            label: 'Glossary',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'glossary',
                },
            ],
        },
    ],
};
